ccflags-y += -I $(srctree)/techpack/camera-legacy-n
ccflags-y += -I $(srctree)/techpack/camera-legacy-n/common
ccflags-y += -I $(srctree)/techpack/camera-legacy-n/msm_vb2
ccflags-y += -I $(srctree)/techpack/camera-legacy-n/camera
ccflags-y += -I $(srctree)/techpack/camera-legacy-n/sensor/io
ccflags-y += -I $(srctree)/techpack/camera-legacy-n/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/ ir_led/ ir_cut/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
