ccflags-y += -Idrivers/media/video/msm
ccflags-y += -I $(srctree)/techpack/camera-legacy-n/common
ccflags-y += -I $(srctree)/techpack/camera-legacy-n
ccflags-y += -I $(srctree)/techpack/camera-legacy-n/pproc/cpp
ccflags-y += -I $(srctree)/techpack/camera-legacy-n/msm_buf_mgr/

obj-$(CONFIG_MSM_FD) += msm_fd_dev.o msm_fd_hw.o
