ccflags-y += -I $(srctree)/techpack/camera-legacy-n
ccflags-y += -I $(srctree)/techpack/camera-legacy-n/common
ccflags-y += -I $(srctree)/techpack/camera-legacy-n/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_ir_led.o
