ccflags-y += -I $(srctree)/techpack/camera-legacy-n
ccflags-y += -I $(srctree)/techpack/camera-legacy-n/common
ccflags-y += -I $(srctree)/techpack/camera-legacy-n/sensor/io
ccflags-y += -I $(srctree)/techpack/camera-legacy-n/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
