ccflags-y += -I $(srctree)/techpack/camera-legacy-n
ccflags-y += -I $(srctree)/techpack/camera-legacy-n/common
ccflags-y += -I $(srctree)/techpack/camera-legacy-n/sensor/io
obj-$(CONFIG_MSM_CCI) += msm_cci.o
